# Generated by Django 3.0.6 on 2020-06-06 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('thumbnail', models.ImageField(default='defo', upload_to='documents/', verbose_name='サムネ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('detail', models.TextField(max_length=255, verbose_name='詳細文')),
                ('ref', models.URLField(max_length=255, verbose_name='外部リンク')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Tag', verbose_name='カテゴリ')),
            ],
        ),
    ]
