# Generated by Django 3.0.6 on 2020-06-06 11:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tag_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='タグ名'),
        ),
    ]
