# Generated by Django 3.0.6 on 2020-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200606_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default=4, max_length=255, verbose_name='タグ名'),
            preserve_default=False,
        ),
    ]
